[tool.poetry]
name = "dashboard-stats"
version = "0.1.0"
description = "A package to produce stats from the ukrdc database to be displayed on the dashboard"
authors = ["Philip Main <Philip.Main@renalregistry.nhs.uk>"]
packages = [
    {include = "dashboard_stats"}
]
license = "MIT"


[tool.poetry.dependencies]
python = "^3.8"
ukrdc-sqla = "^1.10.0" 
SQLAlchemy = "^1.4.40"
python-dotenv = "^0.20.0"
psycopg2-binary = "^2.9.3" # Needed for postgres
pandas = "^1.4.3"


[tool.poetry.dev-dependencies]
black = {version = "^22.1", allow-prereleases = true}
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
