[tox]
envlist = black, mypy, pylint, bandit
skipsdist = True

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
install_command = pip install {opts} {packages}
deps = -r{toxinidir}/requirements.txt

[testenv:black]
description = 'Check code style with Black'
deps =
    black
commands = black scripts/ --check

[testenv:mypy]
description = 'Execute static analysis with mypy (type annotations).'
deps =
    {[testenv]deps}
    mypy
    sqlalchemy-stubs
commands = mypy scripts/

[testenv:pytest]
description = 'Run unit tests with Pytest.'
deps = 
    {[testenv]deps}
    pytest
commands =
    pytest --cov=scripts/ --cov-report term-missing --cov-report xml tests/

[testenv:pylint]
description = 'Execute static analysis with pylint.'
deps =
    {[testenv]deps}
    pylint
commands = pylint scripts/

[testenv:bandit]
description = 'Execute static analysis with bandit.'
deps =
    bandit
commands = bandit -r scripts/