[tox]
envlist = black
skipsdist = True

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
install_command = poetry install 


[testenv:black]
description = 'Check code style with Black'
deps =
    black
commands = black stats/ --check

