"""This file contains groupings and mappings of codes used by stats.
Maybe these should be in the database?
"""

# 5 ethnicity group mapping
ETHNIC_GROUP_MAP = {
    "A": "White",
    "B": "White",
    "C": "White",
    "D": "Mixed",
    "E": "Mixed",
    "F": "Mixed",
    "G": "Mixed",
    "H": "Asian",
    "J": "Asian",
    "K": "Asian",
    "L": "Asian",
    "M": "Black",
    "N": "Black",
    "P": "Black",
    "R": "Asian",
    "S": "Other",
    "Z": "Not Stated",
}

# NHS digital gender map
GENDER_GROUP_MAP = {"1": "Male", "2": "Female", "9": "Indeterminate", "X": "Unknown"}

# Primary renal diagnosis groupings
PRD_CODE_MAP = {
    "0": "Miscellaneous renal disorders",
    "10": "Glomerular disease",
    "11": "Glomerular disease",
    "12": "Glomerular disease",
    "13": "Glomerular disease",
    "14": "Glomerular disease",
    "15": "Glomerular disease",
    "16": "Glomerular disease",
    "17": "Glomerular disease",
    "19": "Glomerular disease",
    "20": "Tubulointerstitial disease",
    "22": "Tubulointerstitial disease",
    "21": "Tubulointerstitial disease",
    "23": "Tubulointerstitial disease",
    "24": "Tubulointerstitial disease",
    "25": "Tubulointerstitial disease",
    "30": "Tubulointerstitial disease",
    "31": "Tubulointerstitial disease",
    "32": "Tubulointerstitial disease",
    "33": "Tubulointerstitial disease",
    "34": "Tubulointerstitial disease",
    "39": "Tubulointerstitial disease",
    "40": "Tubulointerstitial disease",
    "41": "Familial / hereditary nephropathies",
    "42": "Familial / hereditary nephropathies",
    "43": "Familial / hereditary nephropathies",
    "49": "Familial / hereditary nephropathies",
    "50": "Glomerular disease",
    "51": "Familial / hereditary nephropathies",
    "52": "Familial / hereditary nephropathies",
    "53": "Familial / hereditary nephropathies",
    "54": "Familial / hereditary nephropathies",
    "59": "Familial / hereditary nephropathies",
    "60": "Tubulointerstitial disease",
    "61": "Tubulointerstitial disease",
    "63": "Tubulointerstitial disease",
    "66": "Tubulointerstitial disease",
    "70": "Glomerular disease",
    "71": "Systemic diseases affecting the kidney",
    "72": "Systemic diseases affecting the kidney",
    "73": "Glomerular disease",
    "74": "Glomerular disease",
    "75": "Systemic diseases affecting the kidney",
    "78": "Glomerular disease",
    "80": "Systemic diseases affecting the kidney",
    "81": "Systemic diseases affecting the kidney",
    "82": "Systemic diseases affecting the kidney",
    "83": "Systemic diseases affecting the kidney",
    "84": "Glomerular disease",
    "85": "Glomerular disease",
    "86": "Glomerular disease",
    "87": "Glomerular disease",
    "88": "Systemic diseases affecting the kidney",
    "90": "Miscellaneous renal disorders",
    "91": "Tubulointerstitial disease",
    "92": "Tubulointerstitial disease",
    "93": "Tubulointerstitial disease",
    "94": "Tubulointerstitial disease",
    "95": "Miscellaneous renal disorders",
    "96": "Miscellaneous renal disorders",
    "99": "Miscellaneous renal disorders",
    "1003": "Glomerular disease",
    "1813": "Tubulointerstitial disease",
    "3604": "Glomerular disease",
    "3615": "Glomerular disease",
    "3627": "Tubulointerstitial disease",
    "3636": "Tubulointerstitial disease",
    "3643": "Miscellaneous renal disorders",
    "3658": "Familial / hereditary nephropathies",
    "3662": "Tubulointerstitial disease",
    "3670": "Tubulointerstitial disease",
    "1019": "Glomerular disease",
    "1026": "Glomerular disease",
    "1035": "Glomerular disease",
    "1042": "Glomerular disease",
    "1057": "Glomerular disease",
    "1061": "Glomerular disease",
    "1074": "Glomerular disease",
    "1088": "Glomerular disease",
    "1090": "Glomerular disease",
    "1100": "Glomerular disease",
    "1116": "Glomerular disease",
    "1128": "Glomerular disease",
    "1137": "Glomerular disease",
    "1144": "Glomerular disease",
    "1159": "Glomerular disease",
    "1163": "Glomerular disease",
    "1171": "Glomerular disease",
    "1185": "Glomerular disease",
    "1192": "Glomerular disease",
    "1205": "Glomerular disease",
    "1214": "Glomerular disease",
    "1222": "Glomerular disease",
    "1233": "Glomerular disease",
    "1246": "Glomerular disease",
    "1251": "Glomerular disease",
    "1267": "Glomerular disease",
    "1279": "Glomerular disease",
    "1298": "Glomerular disease",
    "1308": "Glomerular disease",
    "1312": "Glomerular disease",
    "1320": "Glomerular disease",
    "1331": "Glomerular disease",
    "1349": "Glomerular disease",
    "1354": "Glomerular disease",
    "1365": "Glomerular disease",
    "1377": "Glomerular disease",
    "1383": "Glomerular disease",
    "1396": "Glomerular disease",
    "1401": "Glomerular disease",
    "1417": "Glomerular disease",
    "1429": "Glomerular disease",
    "1438": "Glomerular disease",
    "1440": "Glomerular disease",
    "1455": "Glomerular disease",
    "1464": "Glomerular disease",
    "1472": "Glomerular disease",
    "1486": "Glomerular disease",
    "1493": "Glomerular disease",
    "1504": "Glomerular disease",
    "1515": "Glomerular disease",
    "1527": "Glomerular disease",
    "1536": "Glomerular disease",
    "1543": "Glomerular disease",
    "1558": "Glomerular disease",
    "1562": "Glomerular disease",
    "1570": "Glomerular disease",
    "1589": "Glomerular disease",
    "1591": "Glomerular disease",
    "1602": "Tubulointerstitial disease",
    "1618": "Tubulointerstitial disease",
    "1625": "Tubulointerstitial disease",
    "1639": "Tubulointerstitial disease",
    "1641": "Tubulointerstitial disease",
    "1656": "Tubulointerstitial disease",
    "1660": "Tubulointerstitial disease",
    "1673": "Tubulointerstitial disease",
    "1687": "Tubulointerstitial disease",
    "1694": "Tubulointerstitial disease",
    "1706": "Tubulointerstitial disease",
    "1710": "Tubulointerstitial disease",
    "1723": "Tubulointerstitial disease",
    "1747": "Tubulointerstitial disease",
    "1752": "Tubulointerstitial disease",
    "1768": "Tubulointerstitial disease",
    "1775": "Tubulointerstitial disease",
    "1781": "Tubulointerstitial disease",
    "1799": "Tubulointerstitial disease",
    "1809": "Tubulointerstitial disease",
    "1821": "Tubulointerstitial disease",
    "1832": "Tubulointerstitial disease",
    "1845": "Tubulointerstitial disease",
    "1850": "Tubulointerstitial disease",
    "1866": "Tubulointerstitial disease",
    "1878": "Tubulointerstitial disease",
    "1884": "Tubulointerstitial disease",
    "1897": "Tubulointerstitial disease",
    "1907": "Tubulointerstitial disease",
    "1911": "Tubulointerstitial disease",
    "1924": "Tubulointerstitial disease",
    "1930": "Tubulointerstitial disease",
    "1948": "Tubulointerstitial disease",
    "1953": "Tubulointerstitial disease",
    "1969": "Tubulointerstitial disease",
    "1976": "Tubulointerstitial disease",
    "1982": "Tubulointerstitial disease",
    "1995": "Tubulointerstitial disease",
    "2005": "Tubulointerstitial disease",
    "2014": "Tubulointerstitial disease",
    "2022": "Tubulointerstitial disease",
    "2033": "Tubulointerstitial disease",
    "2046": "Tubulointerstitial disease",
    "2051": "Tubulointerstitial disease",
    "2067": "Tubulointerstitial disease",
    "2079": "Tubulointerstitial disease",
    "2080": "Tubulointerstitial disease",
    "2098": "Tubulointerstitial disease",
    "2108": "Tubulointerstitial disease",
    "2112": "Tubulointerstitial disease",
    "2120": "Tubulointerstitial disease",
    "2131": "Tubulointerstitial disease",
    "2149": "Tubulointerstitial disease",
    "2154": "Tubulointerstitial disease",
    "2165": "Tubulointerstitial disease",
    "2177": "Tubulointerstitial disease",
    "2183": "Tubulointerstitial disease",
    "2196": "Tubulointerstitial disease",
    "2203": "Tubulointerstitial disease",
    "2219": "Tubulointerstitial disease",
    "2226": "Tubulointerstitial disease",
    "2235": "Tubulointerstitial disease",
    "2242": "Tubulointerstitial disease",
    "2257": "Tubulointerstitial disease",
    "2261": "Tubulointerstitial disease",
    "2274": "Tubulointerstitial disease",
    "2288": "Tubulointerstitial disease",
    "2290": "Tubulointerstitial disease",
    "2300": "Tubulointerstitial disease",
    "2316": "Systemic diseases affecting the kidney",
    "2328": "Systemic diseases affecting the kidney",
    "2337": "Systemic diseases affecting the kidney",
    "2344": "Systemic diseases affecting the kidney",
    "2359": "Systemic diseases affecting the kidney",
    "2363": "Systemic diseases affecting the kidney",
    "2371": "Systemic diseases affecting the kidney",
    "2385": "Systemic diseases affecting the kidney",
    "2392": "Systemic diseases affecting the kidney",
    "2407": "Systemic diseases affecting the kidney",
    "2411": "Systemic diseases affecting the kidney",
    "2424": "Systemic diseases affecting the kidney",
    "2430": "Systemic diseases affecting the kidney",
    "2448": "Systemic diseases affecting the kidney",
    "2453": "Systemic diseases affecting the kidney",
    "2469": "Systemic diseases affecting the kidney",
    "2476": "Systemic diseases affecting the kidney",
    "2482": "Systemic diseases affecting the kidney",
    "2495": "Systemic diseases affecting the kidney",
    "2509": "Systemic diseases affecting the kidney",
    "2513": "Systemic diseases affecting the kidney",
    "2521": "Systemic diseases affecting the kidney",
    "2532": "Systemic diseases affecting the kidney",
    "2545": "Systemic diseases affecting the kidney",
    "2550": "Systemic diseases affecting the kidney",
    "2566": "Systemic diseases affecting the kidney",
    "2578": "Systemic diseases affecting the kidney",
    "2584": "Systemic diseases affecting the kidney",
    "2597": "Systemic diseases affecting the kidney",
    "2606": "Systemic diseases affecting the kidney",
    "2610": "Systemic diseases affecting the kidney",
    "2623": "Systemic diseases affecting the kidney",
    "2634": "Systemic diseases affecting the kidney",
    "2647": "Systemic diseases affecting the kidney",
    "2652": "Systemic diseases affecting the kidney",
    "2668": "Systemic diseases affecting the kidney",
    "2675": "Systemic diseases affecting the kidney",
    "2681": "Systemic diseases affecting the kidney",
    "2699": "Systemic diseases affecting the kidney",
    "2702": "Systemic diseases affecting the kidney",
    "2718": "Familial / hereditary nephropathies",
    "2725": "Familial / hereditary nephropathies",
    "2739": "Familial / hereditary nephropathies",
    "2741": "Familial / hereditary nephropathies",
    "2756": "Familial / hereditary nephropathies",
    "2760": "Familial / hereditary nephropathies",
    "2773": "Familial / hereditary nephropathies",
    "2787": "Familial / hereditary nephropathies",
    "2794": "Familial / hereditary nephropathies",
    "2804": "Familial / hereditary nephropathies",
    "2815": "Familial / hereditary nephropathies",
    "2827": "Familial / hereditary nephropathies",
    "2836": "Familial / hereditary nephropathies",
    "2843": "Familial / hereditary nephropathies",
    "2858": "Familial / hereditary nephropathies",
    "2862": "Familial / hereditary nephropathies",
    "2870": "Familial / hereditary nephropathies",
    "2889": "Familial / hereditary nephropathies",
    "2891": "Familial / hereditary nephropathies",
    "2901": "Familial / hereditary nephropathies",
    "2917": "Familial / hereditary nephropathies",
    "2929": "Familial / hereditary nephropathies",
    "2938": "Familial / hereditary nephropathies",
    "2940": "Familial / hereditary nephropathies",
    "2955": "Familial / hereditary nephropathies",
    "2964": "Familial / hereditary nephropathies",
    "2972": "Familial / hereditary nephropathies",
    "2986": "Familial / hereditary nephropathies",
    "2993": "Familial / hereditary nephropathies",
    "3000": "Familial / hereditary nephropathies",
    "3016": "Familial / hereditary nephropathies",
    "3028": "Familial / hereditary nephropathies",
    "3037": "Familial / hereditary nephropathies",
    "3044": "Familial / hereditary nephropathies",
    "3059": "Familial / hereditary nephropathies",
    "3063": "Familial / hereditary nephropathies",
    "3071": "Familial / hereditary nephropathies",
    "3085": "Familial / hereditary nephropathies",
    "3092": "Familial / hereditary nephropathies",
    "3102": "Familial / hereditary nephropathies",
    "3118": "Familial / hereditary nephropathies",
    "3125": "Familial / hereditary nephropathies",
    "3139": "Familial / hereditary nephropathies",
    "3141": "Familial / hereditary nephropathies",
    "3156": "Familial / hereditary nephropathies",
    "3160": "Familial / hereditary nephropathies",
    "3173": "Familial / hereditary nephropathies",
    "3187": "Familial / hereditary nephropathies",
    "3194": "Familial / hereditary nephropathies",
    "3207": "Familial / hereditary nephropathies",
    "3211": "Familial / hereditary nephropathies",
    "3224": "Familial / hereditary nephropathies",
    "3230": "Familial / hereditary nephropathies",
    "3248": "Familial / hereditary nephropathies",
    "3253": "Familial / hereditary nephropathies",
    "3269": "Familial / hereditary nephropathies",
    "3276": "Familial / hereditary nephropathies",
    "3282": "Familial / hereditary nephropathies",
    "3295": "Familial / hereditary nephropathies",
    "3305": "Familial / hereditary nephropathies",
    "3314": "Familial / hereditary nephropathies",
    "3322": "Familial / hereditary nephropathies",
    "3333": "Familial / hereditary nephropathies",
    "3346": "Familial / hereditary nephropathies",
    "3351": "Familial / hereditary nephropathies",
    "3367": "Familial / hereditary nephropathies",
    "3379": "Familial / hereditary nephropathies",
    "3380": "Miscellaneous renal disorders",
    "3398": "Miscellaneous renal disorders",
    "3403": "Miscellaneous renal disorders",
    "3419": "Miscellaneous renal disorders",
    "3426": "Miscellaneous renal disorders",
    "3435": "Miscellaneous renal disorders",
    "3442": "Miscellaneous renal disorders",
    "3457": "Miscellaneous renal disorders",
    "3461": "Miscellaneous renal disorders",
    "3474": "Miscellaneous renal disorders",
    "3488": "Miscellaneous renal disorders",
    "3490": "Miscellaneous renal disorders",
    "3501": "Miscellaneous renal disorders",
    "3517": "Miscellaneous renal disorders",
    "3529": "Miscellaneous renal disorders",
    "3538": "Miscellaneous renal disorders",
    "3540": "Miscellaneous renal disorders",
    "3555": "Miscellaneous renal disorders",
    "3564": "Miscellaneous renal disorders",
    "3572": "Miscellaneous renal disorders",
    "3689": "Tubulointerstitial disease",
    "3691": "Miscellaneous renal disorders",
    "3708": "Miscellaneous renal disorders",
    "3712": "Miscellaneous renal disorders",
    "3720": "Miscellaneous renal disorders",
    "3731": "Familial / hereditary nephropathies",
    "3749": "Glomerular disease",
}
