"""
The aim of this script is to compare the cohort generated by dashboard stats to
the one produced by the stats team for the annual report. 
"""



import os 
from dotenv import load_dotenv
import datetime as dt
from ukrdc_stats.calculators.dialysis import DialysisStatsCalculator
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine, select
import pandas as pd # requires openpyxl
from pathlib import Path
from ukrdc_sqla.ukrdc import PatientNumber, Treatment, ModalityCodes, Patient, PatientRecord

def write_treatments(nhs_nos,session):

    query = (
        select(
            PatientRecord.pid,
            PatientNumber.patientid,
            PatientRecord.sendingfacility, 
            PatientRecord.sendingextract,
            Treatment.healthcarefacilitycode,
            Treatment.admissionsourcecode,
            Treatment.admissionsourcecodestd,
            Treatment.admitreasoncode,
            Treatment.admitreasoncodestd,
            Treatment.qbl05,
            Treatment.hdp04,
            Treatment.dischargereasoncode,
            Treatment.dischargelocationcodestd,
            ModalityCodes.acute,
            ModalityCodes.registry_code_type,
            Patient.deathtime,
            Treatment.fromtime,
            Treatment.totime
        )
        .select_from(Treatment)
        .join(PatientRecord, PatientRecord.pid == Treatment.pid)
        .join(ModalityCodes, ModalityCodes.registry_code == Treatment.admitreasoncode)
        .join(Patient, Patient.pid == Treatment.pid)
        .join(PatientNumber, PatientNumber.pid == Treatment.pid)
        .where(PatientNumber.patientid.in_(nhs_nos))
    )

    return pd.DataFrame(session.execute(query).all()).drop_duplicates()




ENV_FILE:str = ".env"
RENAL_CENTRE:str = "RJZ"
COHORT:str = "incident"
YEAR:int = 2022 # report year 
OUTPUT_FILE_NAME:str = f"{COHORT}_{YEAR}_{RENAL_CENTRE}_report.xlsx"



root_path = Path(".do_not_commit")

# load up annual report cohort
file_path = root_path / f"{COHORT}_{YEAR}_{RENAL_CENTRE}.xlsx"
output_file = root_path / OUTPUT_FILE_NAME
# load into pandas 
annual_report = pd.read_excel(file_path).astype(str)

# Check if .env file exists
if not os.path.isfile(ENV_FILE):
    raise Exception("env file doesn't exist")
    

# Load the .env file fire up session etc
load_dotenv(ENV_FILE)

    
ukrdc_host = os.getenv('UKRDC_HOST')
ukrdc_port = os.getenv('UKRDC_PORT')
ukrdc_user = os.getenv('UKRDC_USER')
ukrdc_name = os.getenv('UKRDC_NAME')
ukrdc_password = os.getenv('UKRDC_PASSWORD')

database_url = f"postgresql://{ukrdc_user}:{ukrdc_password}@{ukrdc_host}:{ukrdc_port}/{ukrdc_name}"
engine = create_engine(database_url)
with sessionmaker(bind=engine, autocommit=False)() as session: 
    calculator = DialysisStatsCalculator(
        session, 
        RENAL_CENTRE, 
        from_time=dt.datetime(YEAR-1, 12, 31), 
        to_time=dt.datetime(YEAR, 12, 31)
    )

    cohort_report = calculator.generate_cohort_report("incident", include_ni=True).table.to_pandas()
    cohort  = calculator._patient_cohort
    acute_pids = [
        "1000594391",
        "1000755600",
        "1000860239"
    ]
    acute = cohort[cohort.pid.isin(acute_pids)]
    print(acute[["pid","healthcarefacilitycode","admitreasoncode", "is_chronic", "incident", "prevalent", "registry_code_type", "deathtime", "timeline_length", "life_length"]])

    combined_report = pd.merge(cohort_report, annual_report, on="nhsno", how='outer', indicator=True)


    with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
        # Sheet 1: Combined report (including indicator to show which data comes from where)
        combined_report.to_excel(writer, sheet_name='Combined Report', index=False)
        
        # Sheet 2: Rows where 'trtstart' is different from 'admitreasoncode'
        diff_trtstart_admitreason = combined_report[
            (combined_report['trtstart'] != combined_report['registry_code_type'])
            & (combined_report['_merge'] == "both")
        ]
        diff_trtstart_admitreason.to_excel(writer, sheet_name='Diff trtstart vs admitreason', index=False)
        
        # Sheet 3: Rows only in the UKRDC dataset (left-only rows)
        left_only = combined_report[combined_report['_merge'] == 'left_only']
        left_only.to_excel(writer, sheet_name='UKRDC Only', index=False)
        
        # Sheet 4: Rows only in the Annual Report dataset (right-only rows)
        right_only = combined_report[combined_report['_merge'] == 'right_only']
        right_only.to_excel(writer, sheet_name='Annual Report Only', index=False)

        # Write the treatment records out to 
        ukrdc_nhs_nos = write_treatments(left_only.nhsno.drop_duplicates().to_list(), session)
        ukrdc_nhs_nos.to_excel(writer, sheet_name="UKRDC only Treatments", index=False)
        
        annual_nhs_nos = write_treatments(right_only.nhsno.drop_duplicates().to_list(), session)
        annual_nhs_nos.to_excel(writer, sheet_name="Report only Treatments")