name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v1

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "13"

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.8

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox
        run: poetry run tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
